### ISSUE TITLE
Supported alternatives

### ISSUE THREAD

**Issue by reeganviljoen** [br3nt/proc_evaluate#1]
I am frustrated by this libraries lack of maintenance which has led to a lack of support for ruby 3.0

As a member of the open source community I have decided to fork this repository and release a supported version of this gem that accepts bug reports and continues to support newer version of ruby 

you can view the repo here: https://github.com/reeganviljoen/proc_eval

and install it with: `gem install proc_eval` or `bundle add proc_eval`

**Comment by br3nt** [comment]
Hey @reeganviljoen

Thanks for opening an issue describing your problem.

 I have fixed the problem and published a new version of the gem which will support any Ruby version >= 2.0.

Next time, I suggest:
* Open an issue before you reach the frustration level
* Submit a pull request with a fix so that everyone who currently uses this gem (probably no one) can benefit 

I would also suggest you remove your clone from RubyGems as having two of the same Gem I'm sure will be confusing for the community.

Also, your repo is not showing as a forked version of this repo in GitHub.  This will probably make it difficult to merge in any changes that are made in your clone.

Please feel free to open PRs and make contributions. 😃

**Comment by reeganviljoen** [comment]
@br3nt  I will archive my  repo and yank my gem on a few conditions

1. You only support versions of ruby that are currently supported i.e >2.6
2. You introduce CI testing for all supported versions of ruby (Github actions is free for OSS and is easy to set this up with)
3. Add a code coverage report

I can help you with this if you want

**Comment by reeganviljoen** [comment]
on a side note it would also be beneficial to add a linter like rubocop

**Comment by br3nt** [comment]
Hey @reeganviljoen 

It's taken me a while to work out how to respond to you.  If your modus operandi is ultimatums this won't work. People won't always agree with you 100%.  If you throw ultimatums their way, they won't want to work with you.

So, I'm going to treat your ultimatums as suggestions for improvement.

I agree that it's a good idea to run tests on push and merge requests.  I've added an Action to run tests against the currently supported versions of Ruby.

Ideally, I would have preferred to run tests against all versions of Ruby that the Gem is compatible with (2.0+), but found this to be too onerous, and Actions won't allow testing back that far.  Instead, I have opted to update the Compatibility statement in the README.  If features are added in the future that break this compatibility, then the Gemspec can be updated with the new Ruby version restriction and the major version number bumped.

Adding code coverage is also a good idea.  I'll leave that for you if you're keen.

I'm not generally a fan of tools like Rubocop.  Each codebase has its own culture that is generally maintained by the contributors by evaluating each others' work in Code Reviews and general discussions.  I'm not opposed, just not convinced.

Anyways, I'm going to close this issue as complete.  Please open separate tickets for each item you'd like to continue to discuss.

Thanks for your suggestions for improvement 😃
